name: simplehttpserver
description: A simplehttpserver in beta version.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  args: ^2.3.1
  cli_completion: ^0.3.0
  mason_logger: ^0.2.4
  path: ^1.8.3
  pub_updater: ^0.3.0
  shelf: ^1.4.1
  shelf_proxy: ^1.0.4
  shelf_static: ^1.1.2

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
  
executables:
  simplehttpserver:
